require 'yaml'

default_platform(:ios)

platform :ios do
  lane :upload_testflight do |options|
		changelog = ENV['CHANGELOG'] || ''
		
		puts "Uploading to TestFlight with changelog: #{changelog}"
	end
end