name: Create simulator build

on:
  workflow_call:
    inputs:
      deployment_environment:
        description: "Deployment environment"
        required: false
        type: string
        default: ''
      environment:
        description: "Build environment"
        required: true
        type: string

jobs:
  simulator_build:
    name: Create simulator build
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_environment }}
    timeout-minutes: 5
    outputs:
      run_id: ${{ steps.run-id.outputs.run_id }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - run: echo "hello simulator" > simulator.txt
    - name: Upload archived simulator app
      uses: actions/upload-artifact@v4
      with:
        name: my-simulator-build
        path: simulator.txt