name: Run automation tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_build:
        description: "Skips simulator build job"
        type: boolean
        required: false
        default: false

jobs:
  simulator_build:
    name: Create simulator build
    if: ${{ !inputs.skip_build }}
    uses: ./.github/workflows/simulator-build.yml
    secrets: inherit
    with:
      environment: integration
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [simulator_build]
    if: |
      always() &&
      !contains(needs.*.result, 'cancelled')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Simulator app build
      uses: actions/download-artifact@v4
      with:
        name: my-simulator-build
    - name: Open Simulator app
      run: cat simulator.txt